# .nosana-ci.yml
nosana:
  description: Nosana Deno Template

global:
  image: denoland/deno:latest

  # Git, trigger on these branches
  trigger:
    branch:
      - master

jobs:
  # Init Deno
  - name: install
    commands:
      - deno cache --reload=file: ./mod.ts
      - deno task test
