name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
          restore-keys: ${{ runner.os }}-deno-
          path: /home/runner/.cache/deno/deps/https/deno.land

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: fetch any uncached dependencies
        run: |
          deno cache --reload=file: ./mod.ts

      - name: Run tests
        run: deno task test
      - name: Create coverage report
        run: deno task cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage.lcov
